### ISSUE TITLE
License file

### ISSUE THREAD

**Issue by yourteamneedsadam** [ashedryden/freelance-contract#3]
I'd love to use this but I noticed there wasn't a license file and I figured I'd check in about that first. Any chance you could add one? Thanks!

**Comment by LaurieJ** [comment]
I too would love a licence file on this :) It's great to see more shared docs like this - I've previously worked with https://github.com/frabcus/oec which was very useful too. Thanks for creating!

**Comment by ashedryden** [comment]
Done!

**Comment by LaurieJ** [comment]
Thanks :)
